name: 'squidrouter'
version: '1.0.0'
description: 'Squid Router OpenAPI client'
homepage: 'http://github.com/GeniusVentures/squidrouter-client-dart'
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  collection: '>=1.17.0 <2.0.0'
  http: '>=0.13.0 <2.0.0'
  intl: any
  meta: '>=1.1.8 <2.0.0'
  dio: '>=5.0.0 <6.0.0'
  dotenv: '>=4.0.0 <5.0.0'
dev_dependencies:
  test: ^1.25.8